### ISSUE TITLE
create a serverless REST interface to upload files to S3 from the mobile app

### ISSUE THREAD

**Issue by matin** [cuenca-mx/feedme#1]
#### request

Accepts a multi-part file upload and saves the file to an s3 bucket. Names the file using a guid
receive:
- file content
- content size

#### response

Responds with 201 and
- the uri of the file as `/files/{guid}`
- content size to verify the file was properly uploaded
- sha1 hash to verify the file was properly uploaded

**Comment by pachCode** [comment]
@matin  Te parece si el guid lo pongo como el mismo sha1 del documento?

**Comment by matin** [comment]
> @matin Te parece si el guid lo pongo como el mismo sha1 del documento?

sí, está bien.
